import type { NextPage } from 'next'
import Head from 'next/head'
import { Box, Container, Heading } from '@chakra-ui/react'
import {Nav} from "../components/Nav"

const Home: NextPage = () => {
  return (
    <Container maxWidth={720}>
      <Head>
        <title>みんなのオールタイムベスト</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Nav/>
        <Box>
          <Heading pt={8}>Hi, I'm hukurouo </Heading>
        </Box>
      </main>

    </Container>
  )
}

export default Home
